// src/pages/Products.tsx
import { useState, useMemo } from 'react';
import { Layout } from '@/components/layout/Layout';
import { ProductGrid } from '@/components/products/ProductGrid';
import { sampleProducts } from '@/data/products';
import { Input } from '@/components/ui/input';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Search } from 'lucide-react';

const Products = () => {
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState('all');
  const [sortBy, setSortBy] = useState('name');

  const categories = useMemo(() => {
    const cats = new Set(sampleProducts.map(p => p.category).filter(Boolean));
    return ['all', ...Array.from(cats)] as string[];
  }, []);

  const filteredProducts = useMemo(() => {
    let products = [...sampleProducts];

    // Filter by search
    if (search) {
      products = products.filter(
        p =>
          p.name.toLowerCase().includes(search.toLowerCase()) ||
          p.description.toLowerCase().includes(search.toLowerCase())
      );
    }

    // Filter by category
    if (category !== 'all') {
      products = products.filter(p => p.category === category);
    }

    // Sort
    switch (sortBy) {
      case 'price-asc':
        products.sort((a, b) => a.price - b.price);
        break;
      case 'price-desc':
        products.sort((a, b) => b.price - a.price);
        break;
      case 'name':
      default:
        products.sort((a, b) => a.name.localeCompare(b.name));
    }

    return products;
  }, [search, category, sortBy]);

  return (
    <Layout>
      <div className="container py-12">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="font-display text-4xl md:text-5xl font-bold text-foreground">
            Our Collection
          </h1>
          <p className="mt-4 text-muted-foreground max-w-2xl mx-auto">
            Explore our complete range of premium fabrics, from everyday essentials
            to luxury textiles.
          </p>
        </div>

        {/* Filters */}
        <div className="flex flex-col sm:flex-row gap-4 mb-8">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Search fabrics..."
              value={search}
              onChange={e => setSearch(e.target.value)}
              className="pl-10"
            />
          </div>
          <Select value={category} onValueChange={setCategory}>
            <SelectTrigger className="w-full sm:w-[180px]">
              <SelectValue placeholder="Category" />
            </SelectTrigger>
            <SelectContent>
              {categories.map(cat => (
                <SelectItem key={cat} value={cat}>
                  {cat === 'all' ? 'All Categories' : cat}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Select value={sortBy} onValueChange={setSortBy}>
            <SelectTrigger className="w-full sm:w-[180px]">
              <SelectValue placeholder="Sort by" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="name">Name</SelectItem>
              <SelectItem value="price-asc">Price: Low to High</SelectItem>
              <SelectItem value="price-desc">Price: High to Low</SelectItem>
            </SelectContent>
          </Select>
        </div>

        {/* Results count */}
        <p className="text-sm text-muted-foreground mb-6">
          Showing {filteredProducts.length} product{filteredProducts.length !== 1 ? 's' : ''}
        </p>

        {/* Products Grid */}
        <ProductGrid products={filteredProducts} />
      </div>
    </Layout>
  );
};

export default Products;

// pages/admin/products.vue
<template>
  <div class="space-y-6">
    <div>
      <h1 class="font-display text-3xl font-bold text-foreground">
        Products
      </h1>
      <p class="text-muted-foreground mt-1">
        Manage your product catalog
      </p>
    </div>

    <div class="bg-card rounded-lg shadow-elegant p-6">
      <div class="mb-4 flex items-center gap-4">
        <div class="relative flex-1">
          <Search class="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            v-model="search"
            placeholder="Search products..."
            class="pl-10"
          />
        </div>
        <Button @click="openDialog()">
          <Plus class="mr-2 h-4 w-4" />
          Add Product
        </Button>
      </div>

      <div class="overflow-x-auto">
        <table class="w-full">
          <thead>
            <tr class="border-b border-border">
              <th class="text-left p-4 font-semibold">Name</th>
              <th class="text-left p-4 font-semibold">Category</th>
              <th class="text-left p-4 font-semibold">Price</th>
              <th class="text-left p-4 font-semibold">Stock</th>
              <th class="text-right p-4 font-semibold">Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="product in filteredProducts"
              :key="product.id"
              class="border-b border-border"
            >
              <td class="p-4">{{ product.name }}</td>
              <td class="p-4">{{ product.category || 'General' }}</td>
              <td class="p-4">R{{ product.price.toFixed(2) }}</td>
              <td class="p-4">{{ product.stock }}</td>
              <td class="p-4 text-right">
                <div class="flex justify-end gap-2">
                  <Button variant="ghost" size="icon" @click="openDialog(product)">
                    <Pencil class="h-4 w-4" />
                  </Button>
                  <Button variant="ghost" size="icon" @click="deleteProduct(product.id)">
                    <Trash2 class="h-4 w-4" />
                  </Button>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { Plus, Pencil, Trash2, Search } from 'lucide-vue-next';
import { sampleProducts } from '~/data/products';
import type { Product } from '~/types';
import Button from '~/components/ui/button.vue';
import Input from '~/components/ui/input.vue';
import { useToast } from '~/composables/useToast';

definePageMeta({
  middleware: 'admin',
  layout: 'admin',
});

const { toast } = useToast();
const products = ref<Product[]>(sampleProducts);
const search = ref('');

const filteredProducts = computed(() =>
  products.value.filter(
    p =>
      p.name.toLowerCase().includes(search.value.toLowerCase()) ||
      p.category?.toLowerCase().includes(search.value.toLowerCase())
  )
);

const openDialog = (product?: Product) => {
  toast({
    title: product ? 'Edit Product' : 'Add Product',
    description: 'Product dialog functionality coming soon',
  });
};

const deleteProduct = (id: string) => {
  products.value = products.value.filter(p => p.id !== id);
  toast({
    title: 'Product deleted',
    description: 'The product has been removed.',
  });
};
</script>
