// pages/checkout.vue
<template>
  <div class="container py-12">
    <!-- Back Link -->
    <NuxtLink
      to="/cart"
      class="inline-flex items-center gap-2 text-muted-foreground hover:text-primary transition-colors mb-8"
    >
      <ArrowLeft class="h-4 w-4" />
      Back to Cart
    </NuxtLink>

    <div class="grid lg:grid-cols-2 gap-12">
      <!-- Checkout Form -->
      <div class="animate-fade-up">
        <h1 class="font-display text-3xl font-bold text-foreground mb-8">
          Checkout
        </h1>

        <form @submit.prevent="handleSubmit" class="space-y-8">
          <!-- Contact -->
          <div class="space-y-4">
            <h2 class="font-display text-lg font-semibold">Contact</h2>
            <div class="space-y-2">
              <Label for="email">Email</Label>
              <Input
                id="email"
                v-model="form.email"
                type="email"
                required
              />
            </div>
          </div>

          <!-- Shipping -->
          <div class="space-y-4">
            <h2 class="font-display text-lg font-semibold">Shipping Address</h2>
            <div class="grid grid-cols-2 gap-4">
              <div class="space-y-2">
                <Label for="firstName">First Name</Label>
                <Input
                  id="firstName"
                  v-model="form.firstName"
                  required
                />
              </div>
              <div class="space-y-2">
                <Label for="lastName">Last Name</Label>
                <Input
                  id="lastName"
                  v-model="form.lastName"
                  required
                />
              </div>
            </div>
            <div class="space-y-2">
              <Label for="address">Address</Label>
              <Input
                id="address"
                v-model="form.address"
                required
              />
            </div>
            <div class="grid grid-cols-2 gap-4">
              <div class="space-y-2">
                <Label for="city">City</Label>
                <Input
                  id="city"
                  v-model="form.city"
                  required
                />
              </div>
              <div class="space-y-2">
                <Label for="zip">ZIP Code</Label>
                <Input
                  id="zip"
                  v-model="form.zip"
                  required
                />
              </div>
            </div>
          </div>

          <!-- Payment -->
          <div class="space-y-4">
            <h2 class="font-display text-lg font-semibold flex items-center gap-2">
              <CreditCard class="h-5 w-5" />
              Payment
            </h2>
            <div class="space-y-2">
              <Label for="cardNumber">Card Number</Label>
              <Input
                id="cardNumber"
                v-model="form.cardNumber"
                placeholder="1234 5678 9012 3456"
                required
              />
            </div>
            <div class="grid grid-cols-2 gap-4">
              <div class="space-y-2">
                <Label for="expiry">Expiry</Label>
                <Input
                  id="expiry"
                  v-model="form.expiry"
                  placeholder="MM/YY"
                  required
                />
              </div>
              <div class="space-y-2">
                <Label for="cvc">CVC</Label>
                <Input
                  id="cvc"
                  v-model="form.cvc"
                  placeholder="123"
                  required
                />
              </div>
            </div>
          </div>

          <Button
            type="submit"
            variant="hero"
            size="lg"
            class="w-full"
            :disabled="isProcessing"
          >
            <Lock v-if="!isProcessing" class="mr-2 h-4 w-4" />
            {{ isProcessing ? 'Processing...' : 'Complete Order' }}
          </Button>
        </form>
      </div>

      <!-- Order Summary -->
      <div class="lg:col-span-1">
        <div class="bg-card rounded-lg shadow-elegant p-6 sticky top-24">
          <h2 class="font-display text-xl font-bold text-foreground mb-6">
            Order Summary
          </h2>
          <div class="space-y-4">
            <div v-for="item in items" :key="item.id" class="flex justify-between text-sm">
              <span class="text-muted-foreground">{{ item.product.name }} x{{ item.quantity }}</span>
              <span>R{{ (item.product.price * item.quantity).toFixed(2) }}</span>
            </div>
            <div class="border-t border-border pt-4 space-y-2">
              <div class="flex justify-between text-muted-foreground">
                <span>Subtotal</span>
                <span>R{{ totalPrice.toFixed(2) }}</span>
              </div>
              <div class="flex justify-between text-muted-foreground">
                <span>Shipping</span>
                <span>{{ shipping === 0 ? 'Free' : `R${shipping.toFixed(2)}` }}</span>
              </div>
              <div class="flex justify-between text-lg font-semibold pt-2 border-t border-border">
                <span>Total</span>
                <span class="text-primary">R{{ total.toFixed(2) }}</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { CreditCard, Lock, ArrowLeft } from 'lucide-vue-next';
import Button from '~/components/ui/button.vue';
import Input from '~/components/ui/input.vue';
import Label from '~/components/ui/label.vue';
import { useCart } from '~/composables/useCart';
import { useAuth } from '~/composables/useAuth';
import { useToast } from '~/composables/useToast';

definePageMeta({
  middleware: 'auth',
});

const { items, totalPrice, clearCart } = useCart();
const { user } = useAuth();
const { toast } = useToast();
const isProcessing = ref(false);

const form = ref({
  email: user.value?.email || '',
  firstName: '',
  lastName: '',
  address: '',
  city: '',
  zip: '',
  cardNumber: '',
  expiry: '',
  cvc: '',
});

const shipping = computed(() => totalPrice.value >= 100 ? 0 : 99.99);
const total = computed(() => totalPrice.value + shipping.value);

if (items.value.length === 0) {
  navigateTo('/cart');
}

const handleSubmit = async () => {
  isProcessing.value = true;

  // Simulate payment processing
  await new Promise(resolve => setTimeout(resolve, 2000));

  clearCart();
  toast({
    title: 'Order placed successfully!',
    description: "Thank you for your purchase. You'll receive a confirmation email shortly.",
  });
  navigateTo('/payment-success');
};
</script>

// src/pages/Checkout.tsx
import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { Layout } from '@/components/layout/Layout';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useCart } from '@/context/CartContext';
import { useAuth } from '@/context/AuthContext';
import { toast } from '@/hooks/use-toast';
import { CreditCard, Lock, ArrowLeft } from 'lucide-react';

const Checkout = () => {
  const { items, totalPrice, clearCart } = useCart();
  const { isAuthenticated, user } = useAuth();
  const navigate = useNavigate();
  const [isProcessing, setIsProcessing] = useState(false);

  const [form, setForm] = useState({
    email: user?.email || '',
    firstName: '',
    lastName: '',
    address: '',
    city: '',
    zip: '',
    cardNumber: '',
    expiry: '',
    cvc: '',
  });

  const shipping = totalPrice >= 100 ? 0 : 9.99;
  const total = totalPrice + shipping;

  if (items.length === 0) {
    navigate('/cart');
    return null;
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsProcessing(true);

    // Simulate payment processing
    await new Promise(resolve => setTimeout(resolve, 2000));

    clearCart();
    toast({
      title: "Order placed successfully!",
      description: "Thank you for your purchase. You'll receive a confirmation email shortly.",
    });
    navigate('/payment-success');
  };

  return (
    <Layout hideFooter>
      <div className="container py-12">
        {/* Back Link */}
        <Link
          to="/cart"
          className="inline-flex items-center gap-2 text-muted-foreground hover:text-primary transition-colors mb-8"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to Cart
        </Link>

        <div className="grid lg:grid-cols-2 gap-12">
          {/* Checkout Form */}
          <div className="animate-fade-up">
            <h1 className="font-display text-3xl font-bold text-foreground mb-8">
              Checkout
            </h1>

            <form onSubmit={handleSubmit} className="space-y-8">
              {/* Contact */}
              <div className="space-y-4">
                <h2 className="font-display text-lg font-semibold">Contact</h2>
                <div className="space-y-2">
                  <Label htmlFor="email">Email</Label>
                  <Input
                    id="email"
                    type="email"
                    value={form.email}
                    onChange={e => setForm({ ...form, email: e.target.value })}
                    required
                  />
                </div>
              </div>

              {/* Shipping */}
              <div className="space-y-4">
                <h2 className="font-display text-lg font-semibold">Shipping Address</h2>
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="firstName">First Name</Label>
                    <Input
                      id="firstName"
                      value={form.firstName}
                      onChange={e => setForm({ ...form, firstName: e.target.value })}
                      required
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="lastName">Last Name</Label>
                    <Input
                      id="lastName"
                      value={form.lastName}
                      onChange={e => setForm({ ...form, lastName: e.target.value })}
                      required
                    />
                  </div>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="address">Address</Label>
                  <Input
                    id="address"
                    value={form.address}
                    onChange={e => setForm({ ...form, address: e.target.value })}
                    required
                  />
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="city">City</Label>
                    <Input
                      id="city"
                      value={form.city}
                      onChange={e => setForm({ ...form, city: e.target.value })}
                      required
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="zip">ZIP Code</Label>
                    <Input
                      id="zip"
                      value={form.zip}
                      onChange={e => setForm({ ...form, zip: e.target.value })}
                      required
                    />
                  </div>
                </div>
              </div>

              {/* Payment */}
              <div className="space-y-4">
                <h2 className="font-display text-lg font-semibold flex items-center gap-2">
                  <CreditCard className="h-5 w-5" />
                  Payment
                </h2>
                <div className="space-y-2">
                  <Label htmlFor="cardNumber">Card Number</Label>
                  <Input
                    id="cardNumber"
                    placeholder="4242 4242 4242 4242"
                    value={form.cardNumber}
                    onChange={e => setForm({ ...form, cardNumber: e.target.value })}
                    required
                  />
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="expiry">Expiry Date</Label>
                    <Input
                      id="expiry"
                      placeholder="MM/YY"
                      value={form.expiry}
                      onChange={e => setForm({ ...form, expiry: e.target.value })}
                      required
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="cvc">CVC</Label>
                    <Input
                      id="cvc"
                      placeholder="123"
                      value={form.cvc}
                      onChange={e => setForm({ ...form, cvc: e.target.value })}
                      required
                    />
                  </div>
                </div>
              </div>

              <Button
                type="submit"
                variant="hero"
                size="lg"
                className="w-full"
                disabled={isProcessing}
              >
                {isProcessing ? (
                  'Processing...'
                ) : (
                  <>
                    <Lock className="h-4 w-4 mr-2" />
                    Pay ${total.toFixed(2)}
                  </>
                )}
              </Button>
            </form>
          </div>

          {/* Order Summary */}
          <div className="lg:pl-8 animate-fade-up" style={{ animationDelay: '100ms' }}>
            <div className="bg-secondary/50 rounded-lg p-6 sticky top-24">
              <h2 className="font-display text-xl font-semibold mb-6">
                Order Summary
              </h2>

              <div className="space-y-4 max-h-[300px] overflow-y-auto">
                {items.map(item => (
                  <div key={item.id} className="flex gap-4">
                    <div className="w-16 h-16 rounded-md overflow-hidden flex-shrink-0">
                      <img
                        src={item.product.image_url}
                        alt={item.product.name}
                        className="w-full h-full object-cover"
                      />
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="font-medium text-sm truncate">{item.product.name}</p>
                      <p className="text-xs text-muted-foreground">
                        Qty: {item.quantity} yards
                      </p>
                    </div>
                    <p className="font-medium text-sm">
                      ${(item.product.price * item.quantity).toFixed(2)}
                    </p>
                  </div>
                ))}
              </div>

              <div className="mt-6 pt-6 border-t border-border space-y-3 text-sm">
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Subtotal</span>
                  <span>${totalPrice.toFixed(2)}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Shipping</span>
                  <span>{shipping === 0 ? 'Free' : `$${shipping.toFixed(2)}`}</span>
                </div>
                <div className="flex justify-between text-base font-semibold pt-3 border-t border-border">
                  <span>Total</span>
                  <span className="text-primary">${total.toFixed(2)}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default Checkout;
